FROM r-base:latest as base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    && rm -rf /var/lib/apt/lists/*

FROM base as install

WORKDIR /src

COPY ./src/install.R /src/install.R

RUN Rscript /src/install.R

FROM base as final

COPY --from=install /usr/local/lib/R /usr/local/lib/R

WORKDIR /src

CMD ["R"]
