install.packages("BiocManager")
BiocManager::install("minfi", ask = T)
BiocManager::install("limma", ask = T)
BiocManager::install("IlluminaHumanMethylationEPICanno.ilm10b4.hg19", ask = T)
BiocManager::install("dplyr", ask = T)